### ISSUE TITLE
Better handle :gen_tcp.connect errors in tping

### ISSUE THREAD

**Issue by danielspofford** [fhunleth/toolshed#15]
Relevant code: https://github.com/fhunleth/toolshed/blob/master/lib/toolshed/net.ex#L85

The connect call can return many things: http://erlang.org/doc/man/inet.html#type-posix

But only a few are handled, the rest cause a case clause error. Creating this issue to have a place for discussion regarding whether all return values should be explicitly handled, or if only some of them should be and then the rest get implicitly handled with a catch-all clause.

**Comment by fhunleth** [comment]
My 2 cents is to handle them and print nice messages since I only expect humans to calls this.

**Comment by fhunleth** [comment]
@danielspofford Were you planning on sending a PR over for this?

**Comment by fhunleth** [comment]
Closing out of lack of interest.
