### ISSUE TITLE
exit :: logs a crash from IEx (SSH connection)

### ISSUE THREAD

**Issue by jsimmonds2** [fhunleth/toolshed#25]
Low impact, as the IEx session over SSH is finally terminated.

![image](https://user-images.githubusercontent.com/1224439/59328695-62614800-8d30-11e9-8c15-bb1b484f2191.png)

**Comment by fhunleth** [comment]
Yes! That crash annoys me too and I haven't found a better way to implement `exit`. I'll leave this issue open and hope that a better way turns up.

**Comment by jsimmonds2** [comment]
I'll see what I can come up with `:)`

**Comment by fhunleth** [comment]
Crash log message removed in https://github.com/elixir-lang/elixir/commit/fedcff15977930db980faca51580f1a3a94e9439.
